### ISSUE TITLE
CLOCK_MONOTONIC_RAW is linux-specific

### ISSUE THREAD

**Issue by opsec** [luceracloud/seqtest#11]
So:

``
--- seqtest.c.orig      2016-02-21 09:06:35 UTC
+++ seqtest.c
@@ -78,7 +78,11 @@ uint64_t
 gethrtime(void)
 {
        struct timespec ts;
+#if defined(__FreeBSD__)
+       if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
+#else
        if (clock_gettime(CLOCK_MONOTONIC_RAW, &ts) != 0) {
+#endif
                perror("clock_gettime");
                exit(1);
        }

**Comment by gdamore** [comment]
I need to fix that, but it should be driven out of CMake definitions or checks for the presence of that define.  (E.g. #ifdef CLOCK_MONOTONIC_RAW ... #elif defined(CLOCK_MONOTONIC) ... #else #error) 

Its a real shame that timekeeping is one of the less portable aspects of modern systems.

**Comment by gdamore** [comment]
So CLOCK_MONOTONIC_RAW is actually subptimal.  We should use CLOCK_MONOTONIC; sadly this is going to be more expensive due to "math" performed on the results (scaling properly for adjtime), but its also going to be more accurate.  If you don't like this, get a system with a better clock.
